# Generated by Django 4.2.5 on 2023-09-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('identification_number', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(upload_to='criminal_photos/')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_arrest', models.DateField(blank=True, null=True)),
                ('arrest_location', models.CharField(blank=True, max_length=200, null=True)),
                ('charges', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
