# Generated by Django 4.2.5 on 2023-09-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_criminal_remove_prescription_medicines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='biometric',
            field=models.ImageField(default=2, upload_to='criminal_biometric/'),
            preserve_default=False,
        ),
    ]
